// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
const SUPABASE_URL = "https://pybuyaijybtjomsvaols.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YnV5YWlqeWJ0am9tc3Zhb2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTk5NzQsImV4cCI6MjA2OTk5NTk3NH0.ThsrF3SRcKFKlJeV9a0yooFVix0E0SmuV2npShlABIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});